name: Release-Connector

on: push

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - shell: pwsh
      env:
        CERT_DATA: ${{ secrets.CERT_DATA }}
        CERT_PASS: ${{ secrets.CERT_PASS }}
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
      run: .\build.ps1
      